# Generated by Django 4.2.2 on 2024-09-20 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("CarDekho_app", "0003_showroomlist_alter_carlist_chassisnumber"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carlist",
            name="price",
        ),
        migrations.AddField(
            model_name="carlist",
            name="showroom",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Showrooms",
                to="CarDekho_app.showroomlist",
            ),
        ),
    ]
