# Generated by Django 4.2.2 on 2024-09-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CarDekho_app", "0004_remove_carlist_price_carlist_showroom"),
    ]

    operations = [
        migrations.AddField(
            model_name="carlist",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="carlist",
            name="chassisnumber",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
